name: Stale PRs check

on:
  schedule:
  - cron: '0 * * * *'
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  stale-pr-detect:

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write

    steps:
    - uses: actions/stale@v8
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-close: -1
        days-before-stale: 0
        only-labels: 'Dispatch'

  stale-pr-slack-notifications:

    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
    - uses: KaplanTestPrep/stale-pr-slack-notify@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEB_HOOK: 'https://hooks.slack.com/services/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'
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale_label: Stale